### PR TITLE
Add blocks_til_maturity for force closed channels

### PR DESCRIPTION
**Pull request by hieblmi**
Addresses: https://github.com/edouardparis/lntop/issues/91 Fixes: https://github.com/edouardparis/lntop/issues/90
Tested on mainnet: 
image

### CODE REVIEW

**Comment by hieblmi** [comment]
Renamed row into "Matured in: xxx blocks".

**Review by edouardparis — APPROVED** [review]

**Comment by edouardparis** [comment]
> Renamed row into "Matured in: xxx blocks".

Better ! Thanks !

**Comment by edouardparis** [comment]
Failed multiple time to tip you at tips@allmysats.com :(

**Comment by hieblmi** [comment]
@edouardparis I appreciate the reviews and the tip attempt. Could you try it one more time? :-)

**Comment by hieblmi** [comment]
@edouardparis 🚀🚀🚀

**Pull request merged**
