### PR TITLE
feature: A new forwarding history tab

### PR DESCRIPTION
**Pull request by hieblmi**
Addresses https://github.com/edouardparis/lntop/issues/93

This PR introduces a new menu tab "FWDHIST" that displays the forwarding events including peer alias names, amounts, fees and timestamp.
The events are queried from `lnd`s `ForwardingHistory` rpc that can be configured with `startTime` and `maxNumEvents` in order to adjust the number of events to be returned.

The peer alias lookups are currently part of this PR but the logic can be removed once `v0.16.0` of `lnd` is released as this release will contain the necessary logic(https://github.com/lightningnetwork/lnd/pull/7083) within `ForwardingHistory` to enrich the forwarding events with peer alias names.

image

### CODE REVIEW

**Comment by hieblmi** [comment]
I am actually seeing an issue on mainnet where, with long event lists, the peer alias resolution doesn't seem to work as they are shown blank. Have to take a look.

**Comment by edouardparis** [comment]
Thanks for the feature.
Which version of go are you using ?
```
1.16.4 
go build ./...
../../../go/pkg/mod/github.com/lightningnetwork/lnd@v0.15.4-beta/lncfg/address.go:12:2: //go:build comment without // +build comment 
```

**Comment by hieblmi** [comment]
I am using 1.19.1, 1.16.4 might be too old for lnd v0.15.4.

**Review by edouardparis — APPROVED** [review]

**Comment by edouardparis** [comment]
Thanks for the new feature.
Tested with polar

**Comment by hieblmi** [comment]
Thanks for merging it @edouardparis. Would you be able to tag one more release?

**Pull request merged**
