### PR TITLE
Update module dependencies

### PR DESCRIPTION
**Pull request by mmilata**
Update to current `github.com/lightningnetwork/lnd@v0.12.1-beta`. I have no experience with go modules so please review carefully, though it works for me.

### CODE REVIEW

**Comment by edouardparis** [comment]
Thank you for you interest in the project and for the contributions.
I am thinking about removing the vendor directory. It was relevant three years ago, but now go modules are more stable.
Do you have an opinion about it ?

It will take some time for me to review and try the PRs :pray:

**Comment by mmilata** [comment]
Thank you for this nice project!:) I'm not very knowledgeable about golang but personally don't see a disadvantage to removing vendor directory.

**Comment by edouardparis** [comment]
Hello, everything is fine on my side except the docker build: 
I got: 
```
# github.com/lightningnetwork/lnd/lnwallet
/go/pkg/mod/github.com/lightningnetwork/lnd@v0.12.1-beta/lnwallet/wallet.go:41:45: syntax error: unexpected _000, expecting comma or )
note: module requires Go 1.13
The command '/bin/sh -c go install ./...' returned a non-zero code: 2
```
I fixed it with:
```diff
diff --git a/docker/lntop/Dockerfile b/docker/lntop/Dockerfile
index 05eaafd..4522984 100644
--- a/docker/lntop/Dockerfile
+++ b/docker/lntop/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.12-alpine as builder
+FROM golang:1.13-alpine as builder
 
 # install build dependencies
 RUN apk add --no-cache --update git gcc musl-dev
@@ -19,7 +19,7 @@ RUN go install ./...
 
 # ---------------------------------------------------------------------------------------------------------------------------
 
-FROM golang:1.12-alpine as final
+FROM golang:1.13-alpine as final

```
can you modify the Dockerfile in your PR ?
Thank you

**Comment by mmilata** [comment]
Ah, didn't try the docker build before. Updated.

**Comment by edouardparis** [comment]
Seems good, thank you :clap:

**Pull request merged**
