### PR TITLE
Use readonly macaroon by default

### PR DESCRIPTION
**Pull request by mmilata**
Read-only privileges seems to be sufficient and it's always better to use the least powerful credentials. Been running lntop with the readonly macaroon for a while and didn't notice any problem. Did not test the docker image though.

### CODE REVIEW

**Comment by edouardparis** [comment]
This a good idea, but it may introduce compatibility issue for old version of lnd when the readonly macaroon was not always created.
I will certainly merge this for v0.2 version.
Thank you

**Comment by edouardparis** [comment]
I tested with docker.
https://github.com/edouardparis/lntop/blob/master/docker/lntop/home/initial-config-template.toml
s/admin/readonly
and we are good to go :)

**Comment by mmilata** [comment]
Updated, looking forward to 0.2 release, let me know if there's anything I can do to help make it happen!

**Comment by mmilata** [comment]
Great! I still haven't figured out how to receive payments without linking my node id and github id, feel free to tip here though: https://nixbitcoin.org/btcpayserver/apps/4D1Dxb5cGnXHRgNRBpoaraZKTX3i/pos

**Pull request merged**
