### PR TITLE
Vim style vertical movement

### PR DESCRIPTION
**Pull request by juhi24**
Literally the first thing I tried to do the first time I opened lntop was to move down by pressing 'j'. I'm so used to vim keybindings being available in most CLIs. This PR adds the basic vertical movements you'd expect to find:

j/k: move down/up
g/G: move to top/bottom

I didn't document these anywhere yet as I'm not sure if we want to add them on the help page or not. I'm sure most vimists will intuitively try them anyway as I did.

### CODE REVIEW

**Comment by edouardparis** [comment]
Thank you for this nice addition, I am thinking of removing the `h` help panel to have the full `hjkl` experience.
I will review your PR this weekend.

**Comment by juhi24** [comment]
The full `hjkl` would indeed be great! I think providing a `--help`option instead of a help panel would be sufficient.

**Comment by edouardparis** [comment]
Do you mind to remove the help panel for a full `hjkl` in this PR ?
Thank you again for the contribution

**Comment by juhi24** [comment]
Sure. Likely within a week or two. I hope you don't mind waiting a bit

**Comment by juhi24** [comment]
Had some time already today so I was quicker than I expected. :wink: There might still be room for some cleanup, but everything seems to be functional as intended.

**Comment by juhi24** [comment]
With the minor cleanup in the last commit, I consider it ready in my POW. Unless you find some errors, ofc.

**Comment by edouardparis** [comment]
Works good for me :clap:

**Review by edouardparis — APPROVED** [review]
Tested and approved, please provide link for tip !

**Comment by juhi24** [comment]
Awesome, thanks! You will find all the relevant info on https://amboss.space/node/02957896a4cdbec7618eb6eee478957f7f5acaaa03c7af5179810ddaf9afbb8327

**Comment by edouardparis** [comment]
I tried to tip with Eclair and your lightning-address, but it failed.
It seems that the callback in the response is the same link that your lightning address
``` 
curl https://ln.j24.fi/.well-known/lnurlp/j24            
{"status":"OK","callback":"https://ln.j24.fi/.well-known/lnurlp/j24","tag":"payRequest","maxSendable":100000000,"minSendable":1000,"metadata":"[[\"text/identifier\",\"j24@ln.j24.fi\"],[\"text/plain\",\"Thank you! --j24\"]]","commentAllowed":0}
```

**Comment by juhi24** [comment]
Thanks for trying to tip me and pointing out this problem! It's using fiatjaf's bridgeaddr and it did work before. But I can definitely reproduce the problem now. I put my secondary address on amboss while investigating this (and likely moving to full self-hosting the address instead of using bridgeaddr). Anyway, consider my contribution a tip to you for the great software ;)

**Comment by juhi24** [comment]
Thanks for the tip, much appreciated! :pray: I have some further ideas of a wider UI overhaul that I think you might like. I will be publishing an issue or a PR in the coming weeks.

**Pull request merged**
